### ISSUE TITLE
Problemas com Materiais Digitais do Professor relatados pelo Felipe [1]

### ISSUE THREAD

**Issue by suzanasalama** [hedra-editora/pnld2021#1]
[**CASOS GRAVES**]

PNLD0009 (Akutagawa) 23pgs
Ativ 1, pre-leitura: um pouco confusa
Ativ 2, pre-leitura: texto é um copy-paste da ativ 1, leitura. Enseja reprovação.
REPROVADO: Fica evidente a utilização do recurso copiar-colar. Vale melhorar um pouco a redação das atividades e remover os copy-paste.

PNLD0010 (Pequenos poemas em prosa) 13pgs
Ativ 1: pouquíssimo desenvolvidas. Um parágrafo pra cada atividade. Não se discorre sobre o gênero literário tampouco sugere atividades para trabalhar os aspectos formais da obra. As atividades sugeridas são pouco detalhadas. Falta detalhar a dinâmica concreta a ser realizada com os estudantes, bem como atividades que trabalhem com o próprio texto, explorando aspectos temáticos e formais.
Ativ 2: mesma coisa. descrição das atividades estão extremamente curtas e vagas, sem detalhamento. 
REPROVADO: MANUAL DESENVOLVE POUCO AS ATIVIDADES E NÃO ATINGE O NÚMERO MÍNIMO DE PÁGINAS

PNLD0011 (Stoker) 21pgs
As atividades sugeridas são pouco detalhadas. Falta detalhar a dinâmica concreta a ser realizada com os estudantes, bem como atividades que trabalhem com o próprio texto, explorando aspectos temáticos e formais. A exceção é a Atividade II, leitura, que está mais desenvolvida.
REPROVADO: MANUAL DESENVOLVE POUCO AS ATIVIDADES E NÃO ATINGE O NÚMERO MÍNIMO DE PÁGINAS

PNLD0016 (Luiz Gama) 29pgs
REPROVADO: O manual apenas desenvolve atividades de trabalho com o texto propriamente dito na parte de Aprofundamento. Nas Atividades I e II: atividades sobre temas relacionados à obra, mas nenhuma atividade sobre a especificidade da obra. FALTA: Atividades que orientem o professor a trabalhar com o texto da obra; atividades que trabalhem os aspectos formais da obra; atividades relacionadas ao gênero da obra.
EM SUMA: O centro nervoso da falta é a conexão das atividades genéricas sugeridas nas Atividades I e II com o próprio texto da obra, em sua especificidade. Sugere-se a elaboração de atividades com o próprio texto da obra já nas Atividades I e II, para conectar o tema da escravidão com a OBRA de Luiz Gama. Importante também que as Atividades I e II abordem o gênero literário da obra.

PNLD0021 (O chamado de Cthulhu) NÃO DIAGRAMADO
RIDÍCULO. MANUAL VISIVELMENTE INCOMPLETO. APENAS INICIADO. TEXTO EM CAIXA ALTA. O PIOR DE TODOS ATÉ AGORA.

PNLD0023 (Fernão Cardim) NÃO DIAGRAMADO
CASO GRAVE. MANUAL INCOMPLETO. Atividades 1 e 2 com um parágrafo pra cada. Visivelmente incompleto; apenas iniciado.

PNLD 0027 (Cronicas do Crack) 21pgs
REPROVADO: Nos campos das Atividades I e II, foca-se em temas relacionados ao texto, mas não se sugere atividade com a obra propriamente dita. Valoriza-se bastante os aspectos temáticos, mas explora-se pouco os aspectos formais da obra, como exige o edital. Problema: logo na atividade I, a proposta sugere trabalhar com os estudantes o gênero biografia, quando a obra é um conjunto de crônicas (na parte de aprofundamento, reconhece-se que o gênero a ser trabalhado é a crônica). Isso pode levar a eliminação. Importante corrigir a parte que sugere inserir o texto no gênero da biografia, aproveitando para enriquecer as Atividades I e II com propostas que estimulem o contato com o texto da obra propriamente dita, bem como seus aspectos formais.

PNLD0028 (O peru de natal e outros contos - M Andrade) NÃO DIAGRAMADO
Atividades com um parágrafo cada. Pouco desenvolvidas. Material curto. Cabe desenvolver.

PNLD0029 (Surgimento da noite) 17pgs
REPROVADO: Material não está ruim, mas explora pouco o gênero literário e carece de mais páginas.

PNLD0031: Circo teatro e cordel - Rodolfo NÃO DIAGRAMADO
Cópia dos outros materiais de cordel. Pouca atividade com o próprio texto.

PNLD0032: (Dublinenses - Joice) NÃO DIAGRAMADO.
Atividades curtas, vagas e cópias das atividades do outro manual do Joice. Atividades 1 não propõe atividade com o texto ou com o gênero literário.

PNLD0033 (Ispinho e Fulo) 14pgs
REPROVADO: Material bom, mas bem aquém do número de páginas necessário

PNLD0035 (Hino Afrodite) NÃO DIAGRAMADO
RIDÍCULO. MATERIAL ESTÁ VISIVELMENTE INCOMPLETO, COM TEXTO EM CAIXA ALTA. RASCUNHO. INAPROVÁVEL.

PNLD0036 (Viagens imaginárias) 27pgs
REPROVADO: O manual parece ser uma cópia e cola não revisada do material usado em Demanda do Santo Gral. Há um momento em que o próprio título da obra aparece trocado, como A Demanda do Santo Graal. Além disso, a atividade de pre-leitura sugere trabalhar com o genero da biografia, sem especificar que se trataria de comparação com outro gênero, da própria obra, que não é uma biografia. Isso pode confundir o avaliador. Importante deixar claro qual o genero literário da obra que está sendo trabalhada e propor atividades específicas para ambientar os alunos no gênero literário.

PNLD0037 (Retrato do artista quando jovem). NÃO DIAGRAMADO.
Cópia dos outros manuais com obras de Joice. Atividades 1 genéricas (copiadas em todos do Joice) que não trabalham nenhum conteúdo específico do livro. Poucas atividades que trabalham com o texto propriamente dito.

PNLD0044 (Teogonia)
RIDÍCULO. MATERIAL ESTÁ VISIVELMENTE INCOMPLETO, COM TEXTO EM CAIXA ALTA. RASCUNHO. INAPROVÁVEL.

PNLD0045 (Tipógrafo) 13pgs
GRAVE. EVIDENTE CÓPIA DO PATATIVA. POR VEZES FALA-SE DE A VOZ DO NORDESTE AO INVÉS DO LIVRO EM QUESTÃO.

PNLD0059 (Popol Vuh) 20pgs
O manual não está ruim, mas carece de atividades voltadas a ambientar o aluno nas características formais do texto. 10 páginas a menos.

PNLD0060 (Origens das espécies) 19pgs
11 páginas a menos.

[CASOS DE MENOS GRAVIDADE]

PNLD004 (Zepelin) 29pgs
Alguns elementos extraídos de outros manuais (sobre gênero crônica e relação com redes sociais).
Demarcar interdisciplinariedade.

PNLD006 (demanda do Santo Graal) 27pgs
OK. Talvez um pouco mais de atividade com o próprio texto do livro.

PNLD007 (Nascidos na escravidão) 34pgs
Em Ativ. I, final da pos-leitura, fala-se em 3 narrativas. Mas por que só 3???

PNLD0012 (Vocação de cantor - Oliveira Panelas) FALTA DIAGRAMAR
Material é uma cópia enxugada do Patativa, A voz do nordeste. Atividades ocupam apenas um parágrafo cada, pouco desenvolvidas. O conteúdo das atividades é bom, mas é o mesmo de A voz do nordeste.

PNLD0013 (Robson) 20pgs
MATERIAL BOM, MAS APENAS 20pgs

PNLD0015 (Tratado descritivo do Brasil) 16pgs
Atividades não estão ruins, mas carecem de mais desenvolvimento. Por isso, o material fica muito aquém do número de páginas necessário.

PNLD0017 (O médico e o monstro) NÃO DIAGRAMADO
Atividades se valem bastante do recurso ao dicionário, mas evoluem bem, ganhando complexidade à medida que progridem no trabalho com a obra. Propõem dinâmicas bem concretas e estão bem detalhadas. NÃO ESTÁ DIVIDIDO ENTRE ATIVIDADES PRÉ-LEITURA, LEITURA E PÓS-LEITURA.

PNLD0019 (a voz do nordeste - Patativa) NÃO DIAGRAMADO!!
Conteúdo das atividades ok. Algumas cópias de outros materiais sobre cordel, mas acredito que não prejudica.

PNLD0022 (James Joyce) NÃO DIAGRAMADO
Não está péssimo, mas as atividades, sobretudo as Atividades 1, poderiam ser um pouco mais desenvolvidas. Vale partir do conteúdo existente para melhorar o manual se houver tempo.

PNLD0025 (Zé Vicente) NÃO DIAGRAMADO
Algumas cópias de outros materiais de cordel, sobretudo nas Atividades 1. Caberia melhorar.

PNLD0034 (Historia da provincia de Santa Cruz) NÃO DIAGRAMADO
Atividades curtas, de um parágrafo, mas ok. Valeria dar um fôlego se houver tempo.

PNLD0039 (gENTE DE hEMSO) 17pgs
Manual está ok no geral. Carece de páginas. Atividade 1, pré-leitura, poderia explorar melhor o gênero da obra em questão (limita-se a pesquisa de gêneros literários em geral).

PNLD0040 (Sagas) 17pgs
Algumas cópias de Gente de Hemso, mas no geral ok. Carece de páginas.

PNLD0041 (Feitiço de amor e outros contos)
Carece de páginas. Algumas atividades boas, outras mais curtas e vagas.

PNLD0042 (A morte de Ivan) 23pgs
Material ok. Atividades exploram pouco gênero literário e aspectos formais da obra.

PNLD0043 (Diários de Adão e Eva) 18pgs
Algumas atividades carecem de desenvolvimento. Mas, no geral, ok. Faltam páginas.

PNLD0046 (Viagem em volta do meu quarto) 11pgs
Curto. Carece de revisão. Mas o que tem está ok. Atividades curtas. Poucas páginas.

PNLD0059 (Popol Vuh) 20pgs
APROVADO: Mas o manual carece de atividades voltadas a ambientar o aluno nas características formais do texto.

PNLD0060 (Origens das espécies) 19pgs
CORRIGIR: 1.3 Pós-leitura e não pré-leitura.

PNLD0062 (pequenas prisões??) 27pgs
Título errado. PROBLEMA: NÃO ESTÃO DEMARCADAS AS ATIVIDADES DE PRÉ-LEITURA, LEITURA E PÓS LEITURA.

**Comment by jorgesallum** [comment]
feito
