### ISSUE TITLE
Falta seleção

### ISSUE THREAD

**Issue by jorgesallum** [hedra-editora/pnld2021#25]
https://github.com/hedra-editora/pnld2021/blob/49bf89343a96b0dcf200897445e780b478e5c5ac/_MP/PNLD0046-MP.tex#L700

@reniersilva  será que vc poderia acabar essas referências?

**Comment by jorgesallum** [comment]
@sofiaboldrini dá uma olhada nisso

**Comment by sofiaboldrini** [comment]
> @sofiaboldrini dá uma olhada nisso

@jorgesallum sim! vou complementar com outras referências
