### ISSUE TITLE
PNLD0048-MP-C.png com logo em baixa resolução

### ISSUE THREAD

**Issue by jorgesallum** [hedra-editora/pnld2021#48]
@suzanasalama

**Comment by jorgesallum** [comment]
E o nome do Rogério está incompleto. 

PNLD0048-MP.tex:\newcommand{\colaborador}{{Carlos Rogério Duarte Barreiros}}

**Comment by suzanasalama** [comment]
Já alterei a capa no Git. Acho melhor usarmos o nome curto do Rogério, "Rogério Barreiros". Trocar em todos os textos.
