### ISSUE TITLE
Junto de pro

### ISSUE THREAD

**Issue by jorgesallum** [hedra-editora/pnld2021#55]
@Ana-Lancman 

Juntamente com os prof. 
Junto com os

PNLD0002-MP.tex:525:Junto de professores da área de Ciências Humanas, apresente e discuta com os alunos os aspectos
PNLD0002-MP.tex:694:Junto de professores da área de Ciências Humanas, apresente e discuta com os alunos em sala de
PNLD0004-MP.tex:869:Junto de professores de História, estabeleça uma discussão com os alunos sobre as
PNLD0009-MP.tex:272:Estas narrativas se enquadram no grupo de temas cristãos. Junto de professores
PNLD0014-MP.tex:520:Junto do professor de História, organize as turmas em grupos e proponha que
PNLD0030-MP.tex:510:\item Junto do professor de História, apresente e discuta de forma panorâmica com os

**Comment by Ana-Lancman** [comment]
Pronto
