### ISSUE TITLE
ISBN

### ISSUE THREAD

**Issue by jorgesallum** [hedra-editora/pnld2021#56]
PNLD0001-MP.tex:\newcommand{\issnppub}{978-65-86238-30-3}
PNLD0001-MP.tex:\newcommand{\issnepub}{978-65-86238-31-0}
PNLD0002-MP.tex:\newcommand{\issnppub}{---}
PNLD0002-MP.tex:\newcommand{\issnepub}{---}
PNLD0004-MP.tex:\newcommand{\issnppub}{978-65-88934-04-3}
PNLD0004-MP.tex:\newcommand{\issnepub}{978-65-88934-01-2}
PNLD0005-MP.tex:\newcommand{\issnppub}{978-65-86974-23-2}
PNLD0005-MP.tex:\newcommand{\issnepub}{978-65-86974-19-5}
PNLD0006-MP.tex:\newcommand{\issnppub}{978-65-994304-0-4}
PNLD0006-MP.tex:\newcommand{\issnepub}{978-65-994304-1-1}
PNLD0007-MP.tex:\newcommand{\issnppub}{978-65-89705-03-1}
PNLD0007-MP.tex:\newcommand{\issnepub}{978-65-89705-00-0}
PNLD0008-MP.tex:\newcommand{\issnppub}{---}
PNLD0008-MP.tex:\newcommand{\issnepub}{---}
PNLD0009-MP.tex:\newcommand{\issnppub}{978-65-86238-32-7}
PNLD0009-MP.tex:\newcommand{\issnepub}{978-65-86238-33-4}
PNLD0010-MP.tex:\newcommand{\issnppub}{978-65-994412-1-9}
PNLD0010-MP.tex:\newcommand{\issnepub}{978-65-994412-2-6}
PNLD0011-MP.tex:\newcommand{\issnppub}{978-65-86279-26-9}
PNLD0011-MP.tex:\newcommand{\issnepub}{978-65-86279-25-2}
PNLD0013-MP.tex:\newcommand{\issnppub}{978-65-994304-3-5}
PNLD0013-MP.tex:\newcommand{\issnepub}{978-65-994304-2-8}
PNLD0014-MP.tex:\newcommand{\issnppub}{---}
PNLD0014-MP.tex:\newcommand{\issnepub}{---}
PNLD0015-MP.tex:\newcommand{\issnppub}{978-65-89833-01-7}
PNLD0015-MP.tex:\newcommand{\issnepub}{978-65-89833-00-0}
PNLD0016-MP.tex:\newcommand{\issnppub}{---}
PNLD0016-MP.tex:\newcommand{\issnepub}{---}
PNLD0018-MP.tex:\newcommand{\issnppub}{978-65-551908-5-4}
PNLD0018-MP.tex:\newcommand{\issnepub}{978-65-551908-4-7}
PNLD0020-MP.tex:\newcommand{\issnppub}{---}
PNLD0020-MP.tex:\newcommand{\issnepub}{---}
PNLD0024-MP.tex:\newcommand{\issnppub}{---}
PNLD0024-MP.tex:\newcommand{\issnepub}{---}
PNLD0026-MP.tex:\newcommand{\issnppub}{---}
PNLD0026-MP.tex:\newcommand{\issnepub}{---}
PNLD0027-MP.tex:\newcommand{\issnppub}{---}
PNLD0027-MP.tex:\newcommand{\issnepub}{---}
PNLD0029-MP.tex:\newcommand{\issnppub}{---}
PNLD0029-MP.tex:\newcommand{\issnepub}{---}
PNLD0030-MP.tex:\newcommand{\issnppub}{---}
PNLD0030-MP.tex:\newcommand{\issnepub}{---}
PNLD0033-MP.tex:\newcommand{\issnppub}{---}
PNLD0033-MP.tex:\newcommand{\issnepub}{---}
PNLD0035-MP.tex:\newcommand{\issnppub}{978-65-994439-1-6}
PNLD0035-MP.tex:\newcommand{\issnepub}{978-65-994439-2-3}
PNLD0036-MP.tex:\newcommand{\issnppub}{---}
PNLD0036-MP.tex:\newcommand{\issnepub}{---}
PNLD0038-MP.tex:\newcommand{\issnppub}{---}
PNLD0038-MP.tex:\newcommand{\issnepub}{---}
PNLD0039-MP.tex:\newcommand{\issnppub}{---}
PNLD0039-MP.tex:\newcommand{\issnepub}{---}
PNLD0040-MP.tex:\newcommand{\issnppub}{---}
PNLD0040-MP.tex:\newcommand{\issnepub}{---}
PNLD0041-MP.tex:\newcommand{\issnppub}{978-65-994422-3-0}
PNLD0041-MP.tex:\newcommand{\issnepub}{978-65-994422-0-9}
PNLD0042-MP.tex:\newcommand{\issnppub}{---}
PNLD0042-MP.tex:\newcommand{\issnepub}{---}
PNLD0043-MP.tex:\newcommand{\issnppub}{978-65-89829-02-7}
PNLD0043-MP.tex:\newcommand{\issnepub}{978-65-89829-03-4}
PNLD0045-MP.tex:\newcommand{\imagemCapa}{./images/PNLD0045-01.png} \newcommand{\issnppub}{---}
PNLD0045-MP.tex:\newcommand{\issnepub}{---}
PNLD0046-MP.tex:\newcommand{\issnppub}{---}
PNLD0046-MP.tex:\newcommand{\issnepub}{---}
PNLD0048-MP.tex:\newcommand{\issnppub}{978-65-89833-02-4}
PNLD0048-MP.tex:\newcommand{\issnepub}{978-65-89833-03-1}
PNLD0049-MP.tex:\newcommand{\issnppub}{---}
PNLD0049-MP.tex:\newcommand{\issnepub}{---}
PNLD0050-MP.tex:\newcommand{\issnppub}{---}
PNLD0050-MP.tex:\newcommand{\issnepub}{---}
PNLD0051-MP.tex:\newcommand{\issnppub}{---}
PNLD0051-MP.tex:\newcommand{\issnepub}{---}
PNLD0052-MP.tex:\newcommand{\issnppub}{---}
PNLD0052-MP.tex:\newcommand{\issnepub}{---}
PNLD0053-MP.tex:\newcommand{\issnppub}{---}
PNLD0053-MP.tex:\newcommand{\issnepub}{---}
PNLD0054-MP.tex:\newcommand{\issnppub}{---}
PNLD0054-MP.tex:\newcommand{\issnepub}{---}
PNLD0059-MP.tex:\newcommand{\issnppub}{978-65-86497-32-8}
PNLD0059-MP.tex:\newcommand{\issnepub}{978-85-71260-23-8}
PNLD0060-MP.tex:\newcommand{\issnppub}{---}
PNLD0060-MP.tex:\newcommand{\issnepub}{---}
PNLD0061-MP.tex:\newcommand{\issnppub}{---}
PNLD0061-MP.tex:\newcommand{\issnepub}{---}
PNLD0062-MP.tex:\newcommand{\issnppub}{---}
PNLD0062-MP.tex:\newcommand{\issnepub}{---}

**Comment by suzanasalama** [comment]
@jorgesallum geração de barcodes:

9786586238310
9786586238303
9786599442216
9786599442223
9786588934012
9786588934043
9786586974195
9786586974232
9786599430411
9786599430404 
9786589705000
9786589705031
9786599448102
9786599448133
9786586238334
9786586238327 
9786599441219
9786599441226
9786586279252
9786586279269 
9786599430428
9786599430435
9786599441202
9786599441233
9786589833000
9786589833017
9786589829010
9786589829003
9786555190847
9786555190854
9786599448416
9786599448430
9786586974201
9786586974218
9786588791080
9786588791073
9786589810094
9786589810070
9786586941357
9786586941364
9786599448409
9786599448423
9786599438912
9786599438936 
9786599443923
9786599443916
9786599443909
9786599443930
9786586279276
9786586279283
9786589810087
9786589810049
9786599438905
9786599438929 
9786599442209
9786599442230
9786588934029
9786588934036
9786589829034
9786589829027
9786589705017
9786589705024
9786599448119
9786599448126
9786589833024
9786589833031
9786586862065
9786586862072
9786586862058
9786586862089
9786588791059
9786588791066
9786559660063
9786559660087
9786559660131
9786559660148
9786555190861
9786555190878
9788571260238
9786586497328
9786586497427
9786586497304
9786586598070
9786586598087
9786586941371
9786586941333
